In [2]:
import torch
import torch.nn.functional as F
import torch.nn as nn

# Flatten

- [ ] Arrume

In [3]:
tensor = torch.randn(2, 2, 2, 2).round(decimals=2)

In [4]:
tensor

tensor([[[[ 0.6700, -0.7200],
          [ 0.7500,  0.7000]],

         [[ 0.7100, -0.7400],
          [ 0.7200, -0.3800]]],


        [[[ 1.5600,  0.3300],
          [-0.2200,  0.7000]],

         [[ 0.3200, -0.8400],
          [-0.0800, -0.4000]]]])

In [14]:
tensor.flatten(start_dim=0, end_dim=-1)

tensor([ 0.6700, -0.7200,  0.7500,  0.7000,  0.7100, -0.7400,  0.7200, -0.3800,
         1.5600,  0.3300, -0.2200,  0.7000,  0.3200, -0.8400, -0.0800, -0.4000])

In [5]:
tensor.view(2, -1)

tensor([[ 0.6700, -0.7200,  0.7500,  0.7000,  0.7100, -0.7400,  0.7200, -0.3800],
        [ 1.5600,  0.3300, -0.2200,  0.7000,  0.3200, -0.8400, -0.0800, -0.4000]])

In [6]:
tensor.flatten(start_dim=1, end_dim=2)

tensor([[[ 0.6700, -0.7200],
         [ 0.7500,  0.7000],
         [ 0.7100, -0.7400],
         [ 0.7200, -0.3800]],

        [[ 1.5600,  0.3300],
         [-0.2200,  0.7000],
         [ 0.3200, -0.8400],
         [-0.0800, -0.4000]]])

In [7]:
tensor.flatten(start_dim=1, end_dim=2).shape

torch.Size([2, 4, 2])

In [8]:
torch.flatten(tensor, start_dim=0, end_dim=1)

tensor([[[ 0.6700, -0.7200],
         [ 0.7500,  0.7000]],

        [[ 0.7100, -0.7400],
         [ 0.7200, -0.3800]],

        [[ 1.5600,  0.3300],
         [-0.2200,  0.7000]],

        [[ 0.3200, -0.8400],
         [-0.0800, -0.4000]]])

In [9]:
nn.Flatten()(tensor)

tensor([[ 0.6700, -0.7200,  0.7500,  0.7000,  0.7100, -0.7400,  0.7200, -0.3800],
        [ 1.5600,  0.3300, -0.2200,  0.7000,  0.3200, -0.8400, -0.0800, -0.4000]])

In [10]:
flatten = nn.Flatten(start_dim=1, end_dim=2)  # Achata apenas dimensões 1 e 2

input_tensor = torch.randn(2, 3, 4, 5)  # batch_size=2, canais=3, altura=4, largura=5
output_tensor = flatten(input_tensor)
print("Forma original:", input_tensor.shape)  # torch.Size([2, 3, 4, 5])
print("Forma após Flatten:", output_tensor.shape)  # torch.Size([2, 12, 5])

Forma original: torch.Size([2, 3, 4, 5])
Forma após Flatten: torch.Size([2, 12, 5])


In [11]:
flatten = nn.Flatten(start_dim=1, end_dim=3)  # Achata apenas dimensões 1 e 2

input_tensor = torch.randn(2, 3, 4, 5)  # batch_size=2, canais=3, altura=4, largura=5
output_tensor = flatten(input_tensor)
print("Forma original:", input_tensor.shape)  # torch.Size([2, 3, 4, 5])
print("Forma após Flatten:", output_tensor.shape)  # torch.Size([2, 60])

Forma original: torch.Size([2, 3, 4, 5])
Forma após Flatten: torch.Size([2, 60])


In [12]:
# Aplicando o flatten nas dimensões 1 e 2 (canais e altura)
output_tensor = torch.flatten(input_tensor, start_dim=1, end_dim=2)
print("Forma após Flatten:", output_tensor.shape)  # torch.Size([2, 12, 5])

Forma após Flatten: torch.Size([2, 12, 5])


In [13]:
# Aplicando o flatten nas dimensões 1 e 2 (canais e altura)
output_tensor = torch.flatten(input_tensor, start_dim=1, end_dim=3)
print("Forma após Flatten:", output_tensor.shape)  # torch.Size([2, 60])

Forma após Flatten: torch.Size([2, 60])


# View